-- Run this in Supabase SQL Editor (https://supabase.com/dashboard/project/dvkwljinagywttyhbdop/sql/new)

create table if not exists todos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  text text not null,
  done boolean not null default false,
  created_at timestamp with time zone default now()
);

alter table todos enable row level security;

create policy "Users can view their own todos"
  on todos for select
  using (auth.uid() = user_id);

create policy "Users can insert their own todos"
  on todos for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own todos"
  on todos for update
  using (auth.uid() = user_id);

create policy "Users can delete their own todos"
  on todos for delete
  using (auth.uid() = user_id);